apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  resources:
    inputs:
      - name: repo
        type: git

  workspaces:
  - name: dockerconfig
    description: Includes a docker 'config.json'
    optional: true
    mountPath: /tmp/.docker

  steps:
  - name: check-config
    image: busybox
    workingDir: /workspace/
    script: |
      #!/bin/sh
      pwd
      mkdir -p /workspace/.docker/
      #ln -s /tmp/.docker/.dockerconfigjson /workspace/.docker/config.json
      #echo '{"auths": {"10.250.127.254:7443":{"auth": "YWRtaW5AaGFyYm9yLmxvY2FsOkhhcmJvcjEyMzQ1"}}}' > /workspace/.docker/config.json
      echo '{"auths": {"harbor-core.kube-system.svc.cluster.local":{"auth": "YWRtaW5AaGFyYm9yLmxvY2FsOkhhcmJvcjEyMzQ1"}}}' > /workspace/.docker/config.json
      echo "-- ls -la /workspace/.docker/config.json"
      ls -la /workspace/.docker/    || true
      cat /workspace/.docker/config.json
      cat <<END >> dockerfile
      FROM busybox
      WORKDIR /workspace/
      RUN ls -la
      END
      cat dockerfile
      echo '-- ls -la /etc/docker/'
      #ls -la /etc/default/  || true

  - name: build-and-push
    workingDir: /kaniko/
    image: gcr.io/kaniko-project/executor:v1.7.0
    env:
      - name: DOCKER_CONFIG
        value: /workspace/.docker
    command:
      - /kaniko/executor
      - --dockerfile=dockerfile
      - --context=/workspace
      - --skip-tls-verify-pull
      - --skip-tls-verify
      - --destination=harbor-core.kube-system.svc.cluster.local/test/tekton-test:v2
