apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: task1-run-
spec:
  serviceAccountName: default
  workspaces:
  - name: dockerconfig
    secret:
      secretName: harbor-default-robot

  taskRef:
    name: demo-task

  resources:
    inputs:
      - name: demo-repo
        resourceSpec:
          type: git
          params:
            - name: url
              value: https://github.com/vdudka/ci-test.git
