apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: demo-task-run
spec:
  serviceAccountName: default

  taskRef:
    name: demo-task

  # resources:
  #   inputs:
  #     - name: demo-repo
  #       resourceSpec:
  #         type: git
  #         params:
  #           - name: url
  #             value: https://github.com/vdudka/ci-test
