apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: demo-task-run
spec:
  serviceAccountName: default

  params:
  - name:   git-repositoru-url
    value:  https://github.com/vdudka/ci-test
  - name:   git-image
    value:  registry-1.docker.io/certascale/ci-tool:3.7.1

  taskRef:
    name: demo-task
